version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bluepacs-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - APP_VERSION=1.0.0
      - ENVIRONMENT=development
      - PYTHON_VERSION=3.11
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - bluepacs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: bluepacs-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bluepacs-network

networks:
  bluepacs-network:
    driver: bridge 